#!/bin/bash -e

usage="Usage: $0 <infile.pdf> <vol> <num> <firstpage>"

if [[ $# -ne 4 ]] ; then
  echo "$usage"
  exit -1
fi

# input file
f="$1"
if [[ ! -e "$f" ]] ; then
  echo "Input file \"$f\" missing"
  echo "$usage"
  exit -1
fi
r="${f%.pdf}"



# other parameters
v="$2"
y="$((v+2009))"
n="$3"
fp="$4"
np=`pdfinfo "$f" | grep -i pages | awk '{print $2'}`
#np="$5"
lp="$((fp + np - 1))"

# print parameters for user to check
echo "infile=$f"
echo "year=$y"
echo "vol=$v"
echo "num=$n"
echo "firstpage=$fp"
echo "lastpage=$lp"

# generate a pdf file with nothing but the footer that includes volume
# information and page numbers
texfile="$r-pagenums.tex"
cat <<END > "$texfile"
\\documentclass{jocg}
\\usepackage{graphicx}

\\fancyhead{}
\\fancyfoot[L]{\sf JoCG $v($n), $fp--$lp, $y}
\\fancyfoot[C]{\\thepage}
\\fancyfoot[R]{\href{http://creativecommons.org/licenses/by/3.0/}{\\includegraphics[height=2.2ex]{cc-by}}}
\\renewcommand{\\footrulewidth}{1pt}
\\renewcommand{\\headrulewidth}{0pt}
\\setcounter{page}{$fp}
\\begin{document}
\\
END

i="$fp"
while [[ $((i++)) -lt $lp ]]; do
  echo "\\newpage \ " >> "$texfile"
done
echo "\\end{document}" >> "$texfile"

pdff="${texfile%.tex}.pdf"
pdflatex "$texfile"

of="$r-numbered.pdf"
pdftk "$f" multibackground "$pdff" output "$of"
#pdfovl "$f" "$pdff" "$of"
echo "Output written to \"$of\" - check volume, number, and page numbers"
echo "JoCG $v($n), $fp–$lp, $y"
